# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdcfdaa98d02635ff47d595248bd6ced002554b0e1f25a2d36b36eca78022e21ca278a956290069284878e3746ccc435d4ca4412ed0e887d84cf87f0ca512ed1

test:
  secret_key_base: b0e2ed3e737e3dd2ac861eb39b8b8da854851fb9e7efeb2b2d05ed6d45390da4ae474a301a469c6662c36cf3674da8585a3353f0aba3e68ad7e6d9972949cf48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
